Repository Mikubill/sd-webui-controlnet, pull requests merged in 2023-12, with the labels that each got.

#2348 :bug: Fix dtype issue in IPAdapter for MacOS
  scripts/controlmodel_ipadapter.py
Labels: bug, MacOS

#2293 Add Animal Pose Preprocessor (RTMPose AP-10K)
  annotator/openpose/__init__.py
  annotator/openpose/animalpose.py
  annotator/openpose/cv_ox_det.py
  annotator/openpose/cv_ox_pose.py
  annotator/openpose/types.py
  annotator/openpose/wholebody.py
  scripts/api.py
  scripts/controlnet_ui/openpose_editor.py
  scripts/global_state.py
  scripts/processor.py
  tests/annotator_tests/openpose_tests/json_encode_test.py
  tests/web_api/animal_pose.json
  tests/web_api/render_openpose_json.py
Labels: enhancement

#2365 :wrench: Add option to bypass ControlNet input image crop
  scripts/controlnet.py
Labels: bug

#2346 Quick edit of preprocessor result with photopea
  javascript/photopea.js
  scripts/controlnet.py
  scripts/controlnet_ui/controlnet_ui_group.py
  scripts/controlnet_ui/photopea.py
  style.css
Labels: enhancement
